#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

bspc monitor -d     

bspc config border_width         4
bspc config focused_border_color "#10b981"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

bspc config focus_follows_pointer true

bspc rule -a tooltipwm_class state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# autostart
$HOME/.config/bspwm/while_node.sh &
feh --bg-scale --randomize ~/.config/wallpapers/* &
numlockx &
setxkbmap -option grp:win_space_toggle us,ru &
$HOME/.config/polybar/launch-polybar &
picom &
/opt/xf-lightmap-rlm-2023.04.25-linux-x64/rlm &
